### PR TITLE
Allow align image when zoom in #472

### PR DESCRIPTION
**Pull request by vpetrusevici**
I implemented this feature, but only in %. I don't see any easy solution to use px, because of css. CSS uses rendered size, but canvas real image size. I don't know how to sync them.
Anyway, % is more useful and better than nothing :)

issue #472

### CODE REVIEW

**Comment by Mawi137** [comment]
Looks good! % is indeed a better solution. I didn't think about the difference between the displayed and actual image size.

**Comment by vpetrusevici** [comment]
@Mawi137  thank you for fast approval :)

**Comment by mivanyna** [comment]
Great! I tried to implement in px and haven't found working well solution as well.
Thanks for implementation!)

**Comment by Mawi137** [comment]
Published under version `6.1.0`. Thanks for the PR!

**Pull request merged**
