### PR TITLE
[feature] Add includeBlob as an input

### PR DESCRIPTION
**Pull request by initplatform**
Add includeBlob as an input in order to return image blob in the ImageCroppedEvent.

Keeps backwards compatibility by creating a new async function which gets context and output from existing `crop()` function;

### CODE REVIEW

**Comment by Mawi137** [comment]
Hi there, instead you can also use the `base64ToFile` method exposed by the lib when the `imageCropped` output emits.

I removed the Blob from the output not so long ago for a reason: https://github.com/Mawi137/ngx-image-cropper/releases

So I'm sorry, but I won't accept a PR that adds it again. The `base64ToFile` method will give you the same result.

**Comment by initplatform** [comment]
Ahh I didn't see that. I should have read the release notes. Probably would help to make mention of it in the README. 

My initial thought was to take the base64 passed back, but looking at different implementations it seemed as though there might be platform variations, so thought it might be better to use the canvas since it would be sure to give the correct arrayBuffer back... 

Also interesting that converting in user-land would be faster than dumping from the canvas.. would have though that canvas was faster.

I would say that the changes I made do keep crop returning synchronously, and the changes are backwards compatible. Couldn't hurt to have the option?

Either way, great job on this project. 

All the best!

**Comment by Mawi137** [comment]
There a CHANGELOG.md that points to the releases page, but I’ll add it to the readme as well :)

Edge doesn’t support the toBlob method on canvas so that would need to be polyfilled. I indeed got some poor performance from that method. Using the base64ToFile method is synchronous and fast. Also, you can convert the base64 when you need it to and not each time you change the cropper position.

**Comment by initplatform** [comment]
That is a great point. It does make sense to only convert when ready to export.

**Pull request closed without merging**
