### PR TITLE
Performance: changeDetection

### PR DESCRIPTION
**Pull request by zetti-caletti**
I installed this library and wondered why the cropper slowed down my application so much.
Than I noticed, that on every mousemove, regardless where, the ChangeDetection for the whole application was triggered.
The reason are the HostListeners 'document.mousemove' and 'document.touchmove'. 
This library has over 100.000 downloads every week and I am wondering no one else noticed that before or had any performance issues.
Here I have a demo on stackblitz. Open the console to see the logs while moving the mouse:
[https://stackblitz.com/edit/angular-ivy-b3jycy](https://stackblitz.com/edit/angular-ivy-b3jycy)

I made a commit where the touchmove, mousemove and hammer-gesture are run outside of the angular zone.
Please merge. Thanks :)

### CODE REVIEW

**Comment by Mawi137** [comment]
Hello,
I have though about it changing that behavior, but never actually implemented it. 
I wonder whether the performance upgrade comes from running it outside of Angular or because you changed the @HostListener to a subscription. 
Now you still always listen for mouse and touch move events, but in fact, we are only interested in them, once a mousedown/touchdown event was triggered. So that could be another improvement, to only start the subscription after a mouse down and stop listening once there is a mouseup. Like that, running outside of angular will no longer be necessary, because change detection will only be triggered for mouse move once we clicked on the image cropper itself.

**Comment by Steb95** [comment]
Hi, I've also noticed this issue. The problem is that the hostlisteners (and consequently the ChangeDetection for the whole application) still remain even after the component with the image-cropper element is destroyed/hidden, creating performance issues especially in combination with Angular Router (the app is never completely reloaded and the hostlisteners continue to fire).

Is there any chance that a fix (or this fix in particular) will be applied?

Thank you for your great work!

**Comment by Mawi137** [comment]
Are you sure? Would be strange that hostlisteners wouldn't be destroyed together with the component itself.

**Comment by rbrewer-echelon** [comment]
This is an issue in our codebase as well ... change detection runs on every mousemove, even when the cropper has not been interacted with.

**Pull request closed without merging**
