### PR TITLE
Handled error event in image tag

### LINKED ISSUE #557: Img tag error event not handled
I'm using the image-cropper component on my app with an image URL and and error event handler like in the example below:

```html
<image-cropper ... [imageURL]="imageUrl" (loadImageFailed)="onImageLoadError()"></image-cropper>
```

I would expect the event handler to be called when there's a problem loading the image (such as network connectivity issue) but the the loadImageFailed event does not appear to be triggered in that case.
I've reviewed the code and it looks like the problem is that the **img** tag native **error** event is not being handled.
I think the problem could be solved by simply adding the error handler to the component template (loadImageError visibility may need to be changed as well):

```html
<img
    #sourceImage
    ...
    (error)="loadImageError($event)"
  >
```

### PR DESCRIPTION
**Pull request by kashyapkaki**
Error event in image tag handled.

`(error)="loadImageError($event)"`

This PR should close #557

### CODE REVIEW

**Comment by kashyapkaki** [comment]
Hi @Mawi137, have updated the code for image error handling. Please review and let me know your comments. Also please merge this PR if you feel this code resolves the issue. Thank you!

**Comment by Mawi137** [comment]
Hi,
Thanks for the PR. The build fails because the method you call is private. Can you make it public?

**Comment by kashyapkaki** [comment]
Hi @Mawi137, changed the method to public. Please review and let me know your comments. Thank you!

**Comment by Mawi137** [comment]
Release in version 6.3.4.

**Pull request merged**
