### PR TITLE
Adding Keyboard Access (work in progress, please do not merge)

### PR DESCRIPTION
**Pull request by dj7266**
### What it does?

This PR is to add a keyboard accessibility to the image crop tool. User will be able to tab into the cropping tool and use keyboard to move, resize the cropper. Keys are following.

Move: Arrow buttons
Resize: Shift + Arrow buttons (arrow-up and arrow-right increase the size, and arrow-down and arrow-left decrease the size of the cropper)

### CODE REVIEW

**Comment by Mawi137** [comment]
Hi sorry for the late reply. I just had a look at your code and I was wondering whether it wouldn't be easier to "mimic" the mouse events so all the code there can be reused? This would come down calling `startMove`, `moveImg` and `moveStop`. Like that, most of the code is reused and new features don't have to be implemented twice.

**Comment by dj7266** [comment]
Hello, thank you so much for your comment. Actually, that’s the first approach that I was going to take and tried to use existing functions to mimic the similar behavior for the keyboard accessibility. However, there are a few reasons that I made it separate function.

First of all, the existing move function was strictly using the mouse event so I believe there was no way of reusing the existing move function.

For the resizing, I tried to mimic the keyboard resizing by using 2 cases of existing resize function (for example, use top-right case and then use bottom-left.) This works when the cropper is not near the boarder line of the image, but it doesn’t work in some edge cases. Lets say the cropper is at the top-right corner of the image, and a user is trying to increase the size of the cropper. The cropper size will not grow because y1 and x2 goes out of the image (which means both of the coordinates go out of the image). However this is not the expected behavior. The size of the cropper should grow to bottom and left side. The difference between mouse and keyboard is that mouse only needs to check one pair of coordinates, either (x1 and y1) or (x2 and y2), while keyboard needs to check both coordinate, which is x1, y1, x2, and y2. Therefore, the logic is little different.

Inside of the keyboard functions, I can try to use startMove, moveImg, and moveStop as you indicated above if that makes more sense to you. However I can’t think of any way reusing existing move or resizing functions (or mimicking mouse event) for keyboard access. Let me know if you have any different thoughts or other concerns!

**Comment by Mawi137** [comment]
I see, I think this approach will work fine when there is an aspectRatio, but what if `maintainAspectRatio` is set to false?

**Comment by dj7266** [comment]
That’s a great point. With keyboard, width and height increases or decreases based on the aspect ratio. Therefore, they can’t break the aspect ratio unless the cropper is touching the edge of the image. If cropper is covering the whole width, you still want be able to grow the height, right? I can make the modification.

**Comment by dj7266** [comment]
Nvm, I made a quick hotfix that works with maintainAspectRatio = false. Also, I tried to use startMove, moveImg, moveStop as you suggested but had to modify some of the functions. Let me know your thoughts. Thanks!

**Comment by Mawi137** [comment]
Hi, it's not quite what I meant. If maintainAspectRatio is false, I'd expect to be able to change the width and height separately. What I meant with using those 3 functions, was for example: Shift + ArrowDown triggers the `bottom` event and move it outwards. Shift + Alt + ArrowDown also triggers `bottom` but moves it inwards. Then the same for ArrowUp, Arrow Left and ArrowRight. That way you have a lot more control and you actually provide the same functionality you'd have when using your mouse. What do you think?

**Comment by dj7266** [comment]
Then users would need to change each side separately, top, bottom, left, and right. I think that will give users more control, but it will be very confusing as well. I think all sides should grow or shrink at the same time.

**Comment by dj7266** [comment]
Hi, I talked to our accessibility team today, and they confirmed that your method would also work. I will make those changes and push it again. Thanks for your help.

**Comment by Mawi137** [comment]
I gave it a try as well yesterday actually: https://github.com/Mawi137/ngx-image-cropper/compare/feature/accessibility?expand=1

- Arrows move the cropper by 1px
- Holding shift sets the stepSize to 10px (like in Photoshop)
- Cmd or Ctrl lets you resize the cropper and make ik bigger
- Holding Alt inverts the `position` so you can make the cropper smaller

The only problem I have at the moment is that holding Cmd + Alt + ArrowLeft or ArrowRight changes the tab in Chrome and it doesn't seem to be possible to prevent it. Ctrl + Arrow cannot be used on Mac either.

**Comment by Mawi137** [comment]
Making resize the default and use Cmd to move the image solves that problem though.

**Comment by dj7266** [comment]
Are we changing the keys because we want to move the cropper by 1px, and have Photoshop-like behavior?

**Comment by Mawi137** [comment]
I think it would be nice to be able to change the step size somehow, so you can have the precision of moving it by 1px. However, I also think that moving the cropper should be the default action, but then we are limited in the keyboard combinations.

The default can indeed be 3px, but maybe using the numbers on the keyboard can change the step size so the possibility to make it more precise is there. So that would mean:
- Arrows: moves the cropper
- Shift + Arrows: makes the cropper bigger
- Shift + Alt + Arrows: makes the cropper smaller.
- 1, 2, 3 ... 9: changes the step size (default 3px, but the default can be overriden by using an @Input)

Would that work for you?

**Comment by dj7266** [comment]
I think it's a great idea. I just need to get approvals from our accessibility team. By the way, many keyboard-only users are people with disabilities, which I believe it would be great to make the component screen-reader friendly. Will you be open to that as well?

**Comment by Mawi137** [comment]
Sure!

**Comment by Mawi137** [comment]
I just merged my changes and released version 2.1.0. I'm not sure how you see the screen-reader friendly cropper, so feel free to open a PR for it :)

**Comment by dj7266** [comment]
Sure, I will make one whenever it's ready.

**Pull request closed without merging**
