### PR TITLE
issue #85: added crop on click function

### PR DESCRIPTION
**Pull request by CreativeAcer**

### CODE REVIEW

**Comment by Mawi137** [comment]
Hi @CreativeAcer 
I don't think this needs to be in the image cropper. You could also solve your problem by continuously taking the base64 from the output and assign it to a variable. If you then click the button, you simply take the value from that variable and assign it to another one and show that as the cropped image.

Using the boolean input to trigger a function in the cropper isn't something I like to do. You can also use `@ViewChild(ImageCropperComponent) imageCropper: ImageCropperComponent` in the class containing the image cropper, that gives you direct access to all of the image cropper's public variables and functions.

**Comment by CreativeAcer** [comment]
Hey @Mawi137,
The idea behind the click is to prevent the continuous output. When i was using 4k+ images for example i noticed a performance drop when i frequently and quickly changed the cropper. The click is there to prevent this from happening as the calculations to output the base64 value are only triggered after the onclick.

As to the boolean i agree on your solution. The ViewChild option is in fact a cleaner way to solve it.

anyway, thnx for your reply and code :)

**Comment by Mawi137** [comment]
Hadn't looked at it that way. The `toBlob` method on the canvas is indeed quite slow and you may not need both the file and base64. So if that could be disabled, that would increase the speed quite a lot as well.

Anyhow, I added two options, one is `autoCrop` which is true by default, setting it to false will make it stop emitting at every change to the cropper's position. I also made the `crop` method public so you can access it.

The second option I added is `outputType` and can be set to either `base64`, `file` or `both` so you can disable calling the heavy `toBlob` method if you don't need it.

**Comment by jsdream** [comment]
Thanks, @Mawi137! I find this release useful too.

**Pull request closed without merging**
